#!/usr/bin/env python3
"""Manage durable mathematical problem dossiers.

The tool intentionally uses only the Python standard library so a future session
can validate and update the repository before installing project dependencies.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


DEFAULT_ROOT = Path(__file__).resolve().parents[1]
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
PROBLEM_ID_RE = re.compile(r"^P-(\d{3})$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

WORK_STATUSES = {
    "intake",
    "active",
    "candidate",
    "review",
    "blocked",
    "complete",
    "archived",
}
CLAIM_STATUSES = {
    "open",
    "proof_candidate",
    "proved",
    "disproved",
    "undecidable",
    "withdrawn",
}
TERMINAL_CLAIM_STATUSES = {"proved", "disproved", "undecidable", "withdrawn"}
OBLIGATION_STATUSES = {"open", "in_progress", "resolved", "blocked", "not_needed"}
CLAIM_STATES = {
    "proposed",
    "tested",
    "proved",
    "refuted",
    "assumed",
    "imported",
    "obsolete",
}
PRIOR_PROOF_STATUSES = {"unknown", "reported", "verified"}
README_DASHBOARD_BEGIN = "<!-- BEGIN GENERATED PROBLEM DASHBOARD -->"
README_DASHBOARD_END = "<!-- END GENERATED PROBLEM DASHBOARD -->"

ROOT_FILES = (
    "README.md",
    "AGENTS.md",
    "PROJECT_STATE.md",
    "process/workflow.md",
    "process/statuses.md",
    "process/proof-standard.md",
    "process/review-playbook.md",
    "process/records.md",
    "process/toolkit.md",
    "problems/INDEX.md",
    "problems/_template/problem.json",
    "templates/attempt.md",
    "templates/review.md",
    "templates/session.md",
    "templates/experiment.md",
)
PROBLEM_FILES = (
    "problem.json",
    "STATEMENT.md",
    "STATE.md",
    "CLAIMS.md",
    "OBLIGATIONS.md",
    "PROOF.md",
    "DECISIONS.md",
    "LOG.md",
    "attempts/README.md",
    "reviews/README.md",
    "experiments/README.md",
    "sessions/README.md",
    "references/README.md",
)
RECORD_CONFIG = {
    "attempt": ("A", "attempts", "attempt.md", False),
    "review": ("R", "reviews", "review.md", False),
    "session": ("S", "sessions", "session.md", False),
    "experiment": ("E", "experiments", "experiment.md", True),
}
REVIEW_TYPES = {"logic", "hypotheses", "counterexample", "computation", "exposition"}


class ProofctlError(Exception):
    """Expected user-facing command failure."""


def today() -> str:
    return dt.date.today().isoformat()


def read_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ProofctlError(f"Missing file: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ProofctlError(f"Invalid JSON in {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ProofctlError(f"Expected a JSON object in {path}")
    return value


def write_json(path: Path, value: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def problem_dirs(root: Path) -> list[Path]:
    base = root / "problems"
    if not base.is_dir():
        return []
    return sorted(
        path
        for path in base.iterdir()
        if path.is_dir() and not path.name.startswith("_")
    )


def load_problems(root: Path) -> list[tuple[Path, dict[str, Any]]]:
    loaded: list[tuple[Path, dict[str, Any]]] = []
    for directory in problem_dirs(root):
        manifest = directory / "problem.json"
        if manifest.is_file():
            loaded.append((directory, read_json(manifest)))
    return loaded


def markdown_cell(value: object) -> str:
    return str(value).replace("|", r"\|").replace("\n", " ").strip()


def render_index(problems: list[tuple[Path, dict[str, Any]]]) -> str:
    lines = [
        "<!-- Generated by scripts/proofctl.py index. Do not edit by hand. -->",
        "# Problem index",
        "",
    ]
    if not problems:
        lines.extend(["No problem dossiers have been created.", ""])
        return "\n".join(lines)

    lines.extend(
        [
            "| ID | Problem | Work | Claim | Updated | Next action |",
            "|---|---|---|---|---|---|",
        ]
    )
    for directory, item in sorted(problems, key=lambda pair: pair[1].get("id", "")):
        title = markdown_cell(item.get("title", directory.name))
        link = f"[{title}]({directory.name}/STATE.md)"
        lines.append(
            "| {id} | {link} | `{work}` | `{claim}` | {updated} | {next_action} |".format(
                id=markdown_cell(item.get("id", "?")),
                link=link,
                work=markdown_cell(item.get("work_status", "?")),
                claim=markdown_cell(item.get("claim_status", "?")),
                updated=markdown_cell(item.get("updated", "?")),
                next_action=markdown_cell(item.get("next_action", "")),
            )
        )
    lines.append("")
    return "\n".join(lines)


def prior_proof_label(item: dict[str, Any]) -> str:
    labels = {
        "unknown": "Unknown",
        "reported": "Reported (not inspected)",
        "verified": "Verified",
    }
    return labels.get(str(item.get("prior_proof_status")), "Unknown")


def render_dashboard(problems: list[tuple[Path, dict[str, Any]]]) -> str:
    lines = [README_DASHBOARD_BEGIN, "## Live research status", ""]
    if not problems:
        lines.extend(["No problem dossiers have been created.", README_DASHBOARD_END])
        return "\n".join(lines)

    lines.extend(
        [
            "| ID | Problem | Work | Claim | Previously proven? | LaTeX |",
            "|---|---|---|---|---|---|",
        ]
    )
    for directory, item in sorted(problems, key=lambda pair: pair[1].get("id", "")):
        title = markdown_cell(item.get("title", directory.name))
        proof_link = f"[details](problems/{directory.name}/STATE.md)"
        latex_file = item.get("latex_file")
        pdf_file = item.get("pdf_file")
        artifacts: list[str] = []
        if pdf_file:
            artifacts.append(f"[PDF]({markdown_cell(pdf_file)})")
        if latex_file:
            artifacts.append(f"[TeX]({markdown_cell(latex_file)})")
        latex = " · ".join(artifacts) if artifacts else "—"
        lines.append(
            "| {id} | {title} ({proof_link}) | `{work}` | `{claim}` | {prior} | {latex} |".format(
                id=markdown_cell(item.get("id", "?")),
                title=title,
                proof_link=proof_link,
                work=markdown_cell(item.get("work_status", "?")),
                claim=markdown_cell(item.get("claim_status", "?")),
                prior=prior_proof_label(item),
                latex=latex,
            )
        )
    lines.extend(["", README_DASHBOARD_END])
    return "\n".join(lines)


def write_dashboard(root: Path, problems: list[tuple[Path, dict[str, Any]]]) -> None:
    readme_path = root / "README.md"
    content = readme_path.read_text(encoding="utf-8")
    dashboard = render_dashboard(problems)
    pattern = re.compile(
        rf"{re.escape(README_DASHBOARD_BEGIN)}.*?{re.escape(README_DASHBOARD_END)}",
        flags=re.DOTALL,
    )
    if pattern.search(content):
        content = pattern.sub(dashboard, content)
    else:
        content = content.rstrip() + "\n\n" + dashboard + "\n"
    readme_path.write_text(content, encoding="utf-8")


def write_index(root: Path) -> None:
    destination = root / "problems" / "INDEX.md"
    problems = load_problems(root)
    destination.write_text(render_index(problems), encoding="utf-8")
    write_dashboard(root, problems)


def parse_obligations(path: Path) -> tuple[list[tuple[str, str]], list[str]]:
    obligations: list[tuple[str, str]] = []
    errors: list[str] = []
    seen: set[str] = set()
    if not path.is_file():
        return obligations, errors
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line.startswith("|"):
            continue
        cells = [cell.strip().strip("`") for cell in line.strip("|").split("|")]
        if not cells or not re.fullmatch(r"G\d{3}", cells[0]):
            continue
        if len(cells) < 3:
            errors.append(f"{path}:{line_number}: malformed obligation row")
            continue
        status = cells[2].lower()
        if cells[0] in seen:
            errors.append(f"{path}:{line_number}: duplicate obligation id {cells[0]}")
        seen.add(cells[0])
        if status not in OBLIGATION_STATUSES:
            errors.append(
                f"{path}:{line_number}: invalid obligation status {status!r}"
            )
        obligations.append((cells[0], status))
    return obligations, errors


def validate_claim_ledger(path: Path) -> list[str]:
    errors: list[str] = []
    seen: set[str] = set()
    if not path.is_file():
        return errors
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line.startswith("|"):
            continue
        cells = [cell.strip().strip("`") for cell in line.strip("|").split("|")]
        if not cells or not re.fullmatch(r"[CL]\d{3}", cells[0]):
            continue
        if len(cells) < 5:
            errors.append(f"{path}:{line_number}: malformed claim row")
            continue
        claim_id = cells[0]
        state = cells[3].lower()
        if claim_id in seen:
            errors.append(f"{path}:{line_number}: duplicate claim id {claim_id}")
        seen.add(claim_id)
        if state not in CLAIM_STATES:
            errors.append(f"{path}:{line_number}: invalid claim state {state!r}")
    return errors


def review_count(directory: Path) -> int:
    return len(list((directory / "reviews").glob("R[0-9][0-9][0-9]-*.md")))


def combination_errors(directory: Path, item: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    work = item.get("work_status")
    claim = item.get("claim_status")

    if work in {"candidate", "review"} and claim != "proof_candidate":
        errors.append(f"{work!r} work requires claim_status 'proof_candidate'")
    if work == "complete" and claim not in TERMINAL_CLAIM_STATUSES:
        errors.append("'complete' work requires a terminal claim_status")
    if claim in TERMINAL_CLAIM_STATUSES and work not in {"complete", "archived"}:
        errors.append(f"terminal claim_status {claim!r} requires complete or archived work")

    if work == "review" and review_count(directory) == 0:
        errors.append("'review' work requires at least one review record")

    if work != "complete":
        return errors

    obligations, obligation_errors = parse_obligations(directory / "OBLIGATIONS.md")
    errors.extend(obligation_errors)
    if claim != "withdrawn":
        unresolved = [
            obligation_id
            for obligation_id, status in obligations
            if status in {"open", "in_progress", "blocked"}
        ]
        if unresolved:
            errors.append(
                "completion has unresolved obligations: " + ", ".join(unresolved)
            )

    required_reviews = {"proved": 2, "undecidable": 2, "disproved": 1}.get(claim, 0)
    actual_reviews = review_count(directory)
    if actual_reviews < required_reviews:
        errors.append(
            f"{claim!r} completion requires {required_reviews} review record(s); "
            f"found {actual_reviews}"
        )

    proof_path = directory / "PROOF.md"
    if claim in {"proved", "disproved", "undecidable"} and proof_path.is_file():
        if "Candidate status: none" in proof_path.read_text(encoding="utf-8"):
            errors.append("completion requires an integrated candidate in PROOF.md")
    return errors


def validate_repository(root: Path) -> list[str]:
    errors: list[str] = []
    for relative in ROOT_FILES:
        if not (root / relative).is_file():
            errors.append(f"missing required repository file: {relative}")

    directories = problem_dirs(root)
    loaded: list[tuple[Path, dict[str, Any]]] = []
    for directory in directories:
        for relative in PROBLEM_FILES:
            if not (directory / relative).is_file():
                errors.append(
                    f"{directory.relative_to(root)}: missing required file {relative}"
                )
        manifest_path = directory / "problem.json"
        if not manifest_path.is_file():
            continue
        try:
            item = read_json(manifest_path)
        except ProofctlError as exc:
            errors.append(str(exc))
            continue
        loaded.append((directory, item))

        required_fields = {
            "schema_version",
            "id",
            "slug",
            "title",
            "statement_file",
            "statement_version",
            "work_status",
            "claim_status",
            "created",
            "updated",
            "tags",
            "dependencies",
            "next_action",
            "prior_proof_status",
            "latex_file",
            "pdf_file",
            "latex_engine",
        }
        missing = sorted(required_fields - item.keys())
        if missing:
            errors.append(
                f"{manifest_path.relative_to(root)}: missing fields {', '.join(missing)}"
            )
        if item.get("schema_version") != 1:
            errors.append(f"{manifest_path.relative_to(root)}: schema_version must be 1")
        if not isinstance(item.get("id"), str) or not PROBLEM_ID_RE.fullmatch(
            item.get("id", "")
        ):
            errors.append(f"{manifest_path.relative_to(root)}: invalid problem id")
        if item.get("slug") != directory.name:
            errors.append(
                f"{manifest_path.relative_to(root)}: slug must match directory name"
            )
        if not SLUG_RE.fullmatch(directory.name):
            errors.append(f"{directory.relative_to(root)}: invalid directory slug")
        if not isinstance(item.get("title"), str) or not item.get("title", "").strip():
            errors.append(f"{manifest_path.relative_to(root)}: title must be nonempty")
        if item.get("statement_file") != "STATEMENT.md":
            errors.append(
                f"{manifest_path.relative_to(root)}: statement_file must be STATEMENT.md"
            )
        if item.get("work_status") not in WORK_STATUSES:
            errors.append(
                f"{manifest_path.relative_to(root)}: invalid work_status "
                f"{item.get('work_status')!r}"
            )
        if item.get("claim_status") not in CLAIM_STATUSES:
            errors.append(
                f"{manifest_path.relative_to(root)}: invalid claim_status "
                f"{item.get('claim_status')!r}"
            )
        for field in ("created", "updated"):
            value = item.get(field)
            if not isinstance(value, str) or not DATE_RE.fullmatch(value):
                errors.append(
                    f"{manifest_path.relative_to(root)}: {field} must be YYYY-MM-DD"
                )
                continue
            try:
                dt.date.fromisoformat(value)
            except ValueError:
                errors.append(
                    f"{manifest_path.relative_to(root)}: {field} is not a real date"
                )
        if (
            isinstance(item.get("created"), str)
            and isinstance(item.get("updated"), str)
            and DATE_RE.fullmatch(item["created"])
            and DATE_RE.fullmatch(item["updated"])
            and item["updated"] < item["created"]
        ):
            errors.append(
                f"{manifest_path.relative_to(root)}: updated predates created"
            )
        if not isinstance(item.get("statement_version"), str) or not item.get(
            "statement_version", ""
        ).strip():
            errors.append(
                f"{manifest_path.relative_to(root)}: statement_version must be nonempty"
            )
        if not isinstance(item.get("tags"), list):
            errors.append(f"{manifest_path.relative_to(root)}: tags must be a list")
        if not isinstance(item.get("dependencies"), list):
            errors.append(
                f"{manifest_path.relative_to(root)}: dependencies must be a list"
            )
        if item.get("prior_proof_status") not in PRIOR_PROOF_STATUSES:
            errors.append(
                f"{manifest_path.relative_to(root)}: invalid prior_proof_status "
                f"{item.get('prior_proof_status')!r}"
            )
        latex_file = item.get("latex_file")
        if latex_file is not None and (
            not isinstance(latex_file, str) or not latex_file.endswith(".tex")
        ):
            errors.append(
                f"{manifest_path.relative_to(root)}: latex_file must be null or a .tex path"
            )
        pdf_file = item.get("pdf_file")
        if pdf_file is not None and (
            not isinstance(pdf_file, str) or not pdf_file.endswith(".pdf")
        ):
            errors.append(
                f"{manifest_path.relative_to(root)}: pdf_file must be null or a .pdf path"
            )
        if item.get("latex_engine") is not None and not isinstance(
            item.get("latex_engine"), str
        ):
            errors.append(
                f"{manifest_path.relative_to(root)}: latex_engine must be null or a string"
            )
        if item.get("claim_status") == "proved":
            if not isinstance(latex_file, str) or not (root / latex_file).is_file():
                errors.append(
                    f"{manifest_path.relative_to(root)}: proved status requires an existing latex_file"
                )
            if not isinstance(pdf_file, str) or not (root / pdf_file).is_file():
                errors.append(
                    f"{manifest_path.relative_to(root)}: proved status requires an existing pdf_file"
                )
        if not isinstance(item.get("next_action"), str) or not item.get(
            "next_action", ""
        ).strip():
            errors.append(
                f"{manifest_path.relative_to(root)}: next_action must be nonempty"
            )
        if item.get("work_status") != "complete":
            _, obligation_errors = parse_obligations(directory / "OBLIGATIONS.md")
            errors.extend(obligation_errors)
        errors.extend(validate_claim_ledger(directory / "CLAIMS.md"))
        for path in directory.rglob("*"):
            if path.is_file() and path.suffix in {".md", ".json"}:
                if re.search(
                    r"\{\{[A-Z_]+\}\}", path.read_text(encoding="utf-8")
                ):
                    errors.append(
                        f"{path.relative_to(root)}: unresolved template token"
                    )
        for message in combination_errors(directory, item):
            errors.append(f"{manifest_path.relative_to(root)}: {message}")

    expected_dashboard = render_dashboard(loaded)
    readme_path = root / "README.md"
    if readme_path.is_file() and expected_dashboard not in readme_path.read_text(encoding="utf-8"):
        errors.append("README.md problem dashboard is stale; run proofctl.py index")

    ids: dict[str, Path] = {}
    known_ids = {
        item.get("id")
        for _, item in loaded
        if isinstance(item.get("id"), str)
    }
    for directory, item in loaded:
        problem_id = item.get("id")
        if isinstance(problem_id, str):
            if problem_id in ids:
                errors.append(
                    f"duplicate problem id {problem_id}: "
                    f"{ids[problem_id].relative_to(root)} and "
                    f"{directory.relative_to(root)}"
                )
            ids[problem_id] = directory
        dependencies = item.get("dependencies")
        if isinstance(dependencies, list):
            for dependency in dependencies:
                if dependency not in known_ids:
                    errors.append(
                        f"{directory.relative_to(root)}/problem.json: "
                        f"unknown dependency {dependency!r}"
                    )

    dependency_graph = {
        str(item.get("id")): [
            str(dependency)
            for dependency in item.get("dependencies", [])
            if dependency in known_ids
        ]
        for _, item in loaded
        if isinstance(item.get("dependencies"), list)
    }
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(problem_id: str, trail: list[str]) -> None:
        if problem_id in visiting:
            cycle_start = trail.index(problem_id)
            cycle = trail[cycle_start:]
            message = "problem dependency cycle: " + " -> ".join(cycle)
            if message not in errors:
                errors.append(message)
            return
        if problem_id in visited:
            return
        visiting.add(problem_id)
        for dependency in dependency_graph.get(problem_id, []):
            visit(dependency, trail + [dependency])
        visiting.remove(problem_id)
        visited.add(problem_id)

    for problem_id in dependency_graph:
        visit(problem_id, [problem_id])

    index_path = root / "problems" / "INDEX.md"
    if index_path.is_file():
        expected = render_index(loaded)
        actual = index_path.read_text(encoding="utf-8")
        if actual != expected:
            errors.append("problems/INDEX.md is stale; run proofctl.py index")
    return errors


def resolve_problem(root: Path, slug: str) -> tuple[Path, dict[str, Any]]:
    if not SLUG_RE.fullmatch(slug):
        raise ProofctlError(
            "Problem slug must use lowercase letters, digits, and single hyphens"
        )
    directory = root / "problems" / slug
    if not directory.is_dir():
        raise ProofctlError(f"Unknown problem: {slug}")
    return directory, read_json(directory / "problem.json")


def safe_record_slug(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug[:60].rstrip("-") or "record"


def replace_tokens(text: str, replacements: dict[str, str]) -> str:
    for key, value in replacements.items():
        text = text.replace("{{" + key + "}}", value)
    return text


def next_problem_id(root: Path) -> str:
    numbers: list[int] = []
    for _, item in load_problems(root):
        match = PROBLEM_ID_RE.fullmatch(str(item.get("id", "")))
        if match:
            numbers.append(int(match.group(1)))
    number = max(numbers, default=0) + 1
    if number > 999:
        raise ProofctlError("Problem ID space P-001..P-999 is exhausted")
    return f"P-{number:03d}"


def command_new(args: argparse.Namespace) -> int:
    root: Path = args.root
    slug: str = args.slug
    if not SLUG_RE.fullmatch(slug):
        raise ProofctlError(
            "Slug must use lowercase letters, digits, and single hyphens"
        )
    destination = root / "problems" / slug
    if destination.exists():
        raise ProofctlError(f"Destination already exists: {destination}")
    template = root / "problems" / "_template"
    if not template.is_dir():
        raise ProofctlError(f"Missing problem template: {template}")

    title = args.title or slug.replace("-", " ").title()
    statement = args.statement or (
        "TODO: Replace this intake placeholder with an exact mathematical statement."
    )
    problem_id = next_problem_id(root)
    replacements = {
        "PROBLEM_ID": problem_id,
        "SLUG": slug,
        "TITLE": title,
        "TITLE_JSON": json.dumps(title, ensure_ascii=False),
        "STATEMENT": statement,
        "DATE": today(),
    }

    shutil.copytree(template, destination)
    for path in destination.rglob("*"):
        if path.is_file():
            path.write_text(
                replace_tokens(path.read_text(encoding="utf-8"), replacements),
                encoding="utf-8",
            )
    write_index(root)
    print(f"Created {problem_id} at {destination.relative_to(root)}")
    print(f"Next: create an intake session and normalize {slug}/STATEMENT.md")
    return 0


def next_record_number(directory: Path, prefix: str) -> int:
    pattern = re.compile(rf"^{prefix}(\d{{3}})-")
    numbers: list[int] = []
    for path in directory.iterdir():
        match = pattern.match(path.name)
        if match:
            numbers.append(int(match.group(1)))
    number = max(numbers, default=0) + 1
    if number > 999:
        raise ProofctlError(f"Record ID space {prefix}001..{prefix}999 is exhausted")
    return number


def command_add(args: argparse.Namespace) -> int:
    root: Path = args.root
    problem_directory, manifest = resolve_problem(root, args.slug)
    prefix, subdirectory, template_name, is_directory = RECORD_CONFIG[args.kind]
    records_directory = problem_directory / subdirectory
    number = next_record_number(records_directory, prefix)
    record_id = f"{prefix}{number:03d}"
    record_slug = safe_record_slug(args.title)
    filename = f"{record_id}-{record_slug}"
    if args.kind == "session":
        filename = f"{record_id}-{today()}-{record_slug}"

    template_path = root / "templates" / template_name
    if not template_path.is_file():
        raise ProofctlError(f"Missing record template: {template_path}")
    content = replace_tokens(
        template_path.read_text(encoding="utf-8"),
        {
            "RECORD_ID": record_id,
            "TITLE": args.title,
            "DATE": today(),
            "PROBLEM_ID": str(manifest["id"]),
            "REVIEW_TYPE": "TODO",
            "INDEPENDENCE_MODE": "not declared",
        },
    )
    if is_directory:
        destination = records_directory / filename
        destination.mkdir()
        output_path = destination / "README.md"
    else:
        output_path = records_directory / f"{filename}.md"
    output_path.write_text(content, encoding="utf-8")

    manifest["updated"] = today()
    write_json(problem_directory / "problem.json", manifest)
    write_index(root)
    print(f"Created {output_path.relative_to(root)}")
    print("Remember to reconcile STATE.md, LOG.md, claims, and obligations.")
    return 0


def command_review(args: argparse.Namespace) -> int:
    """Open a required adversarial review and move a candidate into review."""
    root: Path = args.root
    problem_directory, manifest = resolve_problem(root, args.slug)
    if manifest.get("claim_status") != "proof_candidate":
        raise ProofctlError(
            "A review can start only after claim_status is 'proof_candidate'. "
            "First integrate the candidate and use set-status ... candidate "
            "--claim proof_candidate."
        )
    if manifest.get("work_status") in {"complete", "archived"}:
        raise ProofctlError("Cannot open a review for a complete or archived problem")

    records_directory = problem_directory / "reviews"
    record_id = f"R{next_record_number(records_directory, 'R'):03d}"
    output_path = records_directory / f"{record_id}-{safe_record_slug(args.title)}.md"
    template_path = root / "templates" / "review.md"
    if not template_path.is_file():
        raise ProofctlError(f"Missing record template: {template_path}")
    content = replace_tokens(
        template_path.read_text(encoding="utf-8"),
        {
            "RECORD_ID": record_id,
            "TITLE": args.title,
            "DATE": today(),
            "PROBLEM_ID": str(manifest["id"]),
            "REVIEW_TYPE": args.review_type,
            "INDEPENDENCE_MODE": "fresh-context independent review",
        },
    )
    output_path.write_text(content, encoding="utf-8")

    manifest["work_status"] = "review"
    manifest["updated"] = today()
    manifest["next_action"] = (
        f"Complete {record_id} as a fresh-context {args.review_type} audit; "
        "turn every critical or major finding into an obligation."
    )
    write_json(problem_directory / "problem.json", manifest)
    write_index(root)
    print(f"Started {output_path.relative_to(root)}")
    print("Status changed to review. Assign this to a fresh reviewer context.")
    return 0


def command_typeset(args: argparse.Namespace) -> int:
    """Compile a dossier's standalone LaTeX source into a PDF with Tectonic."""
    root: Path = args.root
    problem_directory, manifest = resolve_problem(root, args.slug)
    latex_file = manifest.get("latex_file")
    if not isinstance(latex_file, str) or not latex_file.endswith(".tex"):
        raise ProofctlError("This problem has no LaTeX source declared in latex_file")
    source = root / latex_file
    if not source.is_file():
        raise ProofctlError(f"LaTeX source does not exist: {latex_file}")
    tectonic = shutil.which("tectonic")
    if tectonic is None:
        raise ProofctlError(
            "Tectonic is required to produce a PDF. Install it, then rerun this command."
        )

    output_directory = source.parent / "build"
    output_directory.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [tectonic, "--outdir", str(output_directory), "--keep-logs", str(source)],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        raise ProofctlError(f"Tectonic failed:\n{detail}")
    pdf_path = output_directory / f"{source.stem}.pdf"
    if not pdf_path.is_file():
        raise ProofctlError("Tectonic finished without creating the expected PDF")
    version = subprocess.run(
        [tectonic, "--version"], text=True, capture_output=True, check=False
    ).stdout.strip()
    manifest["pdf_file"] = pdf_path.relative_to(root).as_posix()
    manifest["latex_engine"] = version or "tectonic"
    manifest["updated"] = today()
    write_json(problem_directory / "problem.json", manifest)
    write_index(root)
    print(f"Wrote {pdf_path.relative_to(root)}")
    if result.stdout.strip():
        print(result.stdout.strip())
    return 0


def command_set_status(args: argparse.Namespace) -> int:
    root: Path = args.root
    directory, manifest = resolve_problem(root, args.slug)
    candidate = dict(manifest)
    candidate["work_status"] = args.work_status
    if args.claim is not None:
        candidate["claim_status"] = args.claim
    if args.next_action is not None:
        candidate["next_action"] = args.next_action
    candidate["updated"] = today()

    errors = combination_errors(directory, candidate)
    if errors:
        raise ProofctlError("Status update rejected:\n- " + "\n- ".join(errors))
    write_json(directory / "problem.json", candidate)
    write_index(root)
    print(
        f"Updated {candidate['id']}: work={candidate['work_status']}, "
        f"claim={candidate['claim_status']}"
    )
    return 0


def command_index(args: argparse.Namespace) -> int:
    write_index(args.root)
    print("Rebuilt problems/INDEX.md")
    return 0


def command_status(args: argparse.Namespace) -> int:
    problems = load_problems(args.root)
    if not problems:
        print("No problem dossiers.")
        return 0
    for _, item in sorted(problems, key=lambda pair: pair[1].get("id", "")):
        print(
            f"{item.get('id', '?')}  {item.get('slug', '?')}  "
            f"work={item.get('work_status', '?')}  "
            f"claim={item.get('claim_status', '?')}"
        )
        print(f"  next: {item.get('next_action', '')}")
    return 0


def command_validate(args: argparse.Namespace) -> int:
    errors = validate_repository(args.root)
    if errors:
        print(f"Validation failed with {len(errors)} error(s):", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    problem_count = len(load_problems(args.root))
    noun = "dossier" if problem_count == 1 else "dossiers"
    print(f"Validation passed ({problem_count} problem {noun}).")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Create, index, update, and validate mathematical problem dossiers."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=DEFAULT_ROOT,
        help="Repository root (defaults to the parent of this script).",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate_parser = subparsers.add_parser(
        "validate", help="Check repository structure and status invariants."
    )
    validate_parser.set_defaults(func=command_validate)

    status_parser = subparsers.add_parser(
        "status", help="Print the current problem dashboard."
    )
    status_parser.set_defaults(func=command_status)

    index_parser = subparsers.add_parser(
        "index", help="Rebuild the generated problem index."
    )
    index_parser.set_defaults(func=command_index)

    new_parser = subparsers.add_parser("new", help="Create a new problem dossier.")
    new_parser.add_argument("slug")
    new_parser.add_argument("--title")
    new_parser.add_argument(
        "--statement", help="Initial exact statement; may be refined during intake."
    )
    new_parser.set_defaults(func=command_new)

    add_parser = subparsers.add_parser(
        "add", help="Add an attempt, review, session, or experiment record."
    )
    add_parser.add_argument("slug")
    add_parser.add_argument("kind", choices=sorted(RECORD_CONFIG))
    add_parser.add_argument("title")
    add_parser.set_defaults(func=command_add)

    review_parser = subparsers.add_parser(
        "review", help="Start a fresh-context adversarial review of a candidate."
    )
    review_parser.add_argument("slug")
    review_parser.add_argument("title")
    review_parser.add_argument(
        "--type", dest="review_type", choices=sorted(REVIEW_TYPES), required=True
    )
    review_parser.set_defaults(func=command_review)

    typeset_parser = subparsers.add_parser(
        "typeset", help="Compile a dossier's LaTeX source to PDF with Tectonic."
    )
    typeset_parser.add_argument("slug")
    typeset_parser.set_defaults(func=command_typeset)

    set_parser = subparsers.add_parser(
        "set-status", help="Update workflow state and rebuild the index."
    )
    set_parser.add_argument("slug")
    set_parser.add_argument("work_status", choices=sorted(WORK_STATUSES))
    set_parser.add_argument("--claim", choices=sorted(CLAIM_STATUSES))
    set_parser.add_argument("--next", dest="next_action")
    set_parser.set_defaults(func=command_set_status)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.root = args.root.resolve()
    try:
        return int(args.func(args))
    except ProofctlError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
